# Generated by Django 2.1.5 on 2020-02-27 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ready_recipe', '0002_auto_20200227_1221'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='description',
        ),
        migrations.AddField(
            model_name='recipe',
            name='views',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='comment',
            name='recommentations',
            field=models.TextField(max_length=3000),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='completion_time',
            field=models.CharField(choices=[('1', '1-15 minutes'), ('2', '15-30 minutes'), ('3', '30-60 minutes'), ('4', '1-1.30 hours'), ('5', '1.30-2 hours'), ('6', '2-2.30 hours'), ('7', 'More than 2.30 hours')], max_length=30),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='difficulty',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10')], max_length=2),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='instuction',
            field=models.TextField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='portions',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10'), ('11', 'More than 10')], max_length=30),
        ),
    ]
