# Generated by Django 2.1.5 on 2020-02-27 23:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ready_recipe', '0007_auto_20200227_2100'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='owner_id',
            field=models.ForeignKey(default='100', on_delete=django.db.models.deletion.CASCADE, to='ready_recipe.UserProfile'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='owner_id',
            field=models.ForeignKey(default='1000', on_delete=django.db.models.deletion.CASCADE, to='ready_recipe.UserProfile'),
        ),
    ]
