# Generated by Django 2.1.5 on 2020-02-28 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ready_recipe', '0010_auto_20200228_1803'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quantities',
            name='quantity',
            field=models.CharField(blank=True, default=0, max_length=100, null=True),
        ),
    ]
