# Generated by Django 2.1.5 on 2020-02-28 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ready_recipe', '0011_auto_20200228_1822'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='quantities',
            name='quantity',
            field=models.CharField(default=0, max_length=100, null=True),
        ),
    ]
