# Generated by Django 2.1.5 on 2020-03-05 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ready_recipe', '0014_userprofile_saved_recipes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='ingredient',
        ),
    ]
