# Generated by Django 2.1.5 on 2020-03-05 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ready_recipe', '0015_remove_recipe_ingredient'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quantities',
            name='ingredient',
        ),
        migrations.RemoveField(
            model_name='quantities',
            name='recipe',
        ),
        migrations.AddField(
            model_name='recipe',
            name='ingredients',
            field=models.TextField(default='0', max_length=2000),
        ),
        migrations.DeleteModel(
            name='Ingredient',
        ),
        migrations.DeleteModel(
            name='Quantities',
        ),
    ]
