# Generated by Django 2.1.5 on 2020-03-13 19:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ready_recipe', '0019_auto_20200305_2321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='category_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ready_recipe.Category'),
        ),
    ]
