# Generated by Django 2.1.5 on 2020-03-13 21:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ready_recipe', '0020_auto_20200313_1944'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='slug',
        ),
    ]
