# Generated by Django 2.1.5 on 2020-03-25 00:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ready_recipe', '0022_remove_recipe_views'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='user',
            new_name='user1',
        ),
    ]
