# Generated by Django 2.1.5 on 2020-03-25 00:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ready_recipe', '0023_auto_20200325_0014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='user1',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
