# Generated by Django 2.1.5 on 2020-03-25 00:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ready_recipe', '0025_auto_20200325_0048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='recipe_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ready_recipe.Recipe'),
        ),
    ]
